apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-invest-notification
  labels:
    app: scpi-invest-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-invest-notification
  template:
    metadata:
      name: scpi-invest-notification
      labels:
        app: scpi-invest-notification
    spec:
      containers:
        - name: scpi-invest-notification
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: aws-credentials
