apiVersion: v1
kind: Service
metadata:
  name: scpi-invest-notification
spec:
  selector:
    app: scpi-invest-notification
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
